Package.describe({
  summary: "Plugin for easy installation of amcharts free version in meteor projects",
  name: "em0ney:amcharts",
  version: "3.17.3",
  git: "https://github.com/em0ney/meteor-amcharts.git",
  documentation: "README.md"
});

Package.onUse(function (api) {
  // Libraries
  api.addFiles('lib/amcharts.js', 'client', {'bare':true});
  api.addFiles('export.js', 'client');
  api.addFiles('lib/funnel.js', 'client');
  api.addFiles('lib/gauge.js', 'client');
  api.addFiles('lib/pie.js', 'client');
  api.addFiles('lib/radar.js', 'client');
  api.addFiles('lib/serial.js', 'client');
  api.addFiles('lib/xy.js', 'client');
  api.addFiles('lib/gantt.js', 'client');

  // Languages
  api.addFiles('lib/lang/az.js', 'client');
  api.addFiles('lib/lang/bg.js', 'client');
  api.addFiles('lib/lang/de.js', 'client');
  api.addFiles('lib/lang/es.js', 'client');
  api.addFiles('lib/lang/fi.js', 'client');
  api.addFiles('lib/lang/fo.js', 'client');
  api.addFiles('lib/lang/fr.js', 'client');
  api.addFiles('lib/lang/hr.js', 'client');
  api.addFiles('lib/lang/hu.js', 'client');
  api.addFiles('lib/lang/id.js', 'client');
  api.addFiles('lib/lang/is.js', 'client');
  api.addFiles('lib/lang/it.js', 'client');
  api.addFiles('lib/lang/ja.js', 'client');
  api.addFiles('lib/lang/lt.js', 'client');
  api.addFiles('lib/lang/lv.js', 'client');
  api.addFiles('lib/lang/mk.js', 'client');
  api.addFiles('lib/lang/mn.js', 'client');
  api.addFiles('lib/lang/mt.js', 'client');
  api.addFiles('lib/lang/nl.js', 'client');
  api.addFiles('lib/lang/no.js', 'client');
  api.addFiles('lib/lang/pl.js', 'client');
  api.addFiles('lib/lang/pt.js', 'client');
  api.addFiles('lib/lang/ro.js', 'client');
  api.addFiles('lib/lang/ru.js', 'client');
  api.addFiles('lib/lang/rw.js', 'client');
  api.addFiles('lib/lang/sk.js', 'client');
  api.addFiles('lib/lang/so.js', 'client');
  api.addFiles('lib/lang/th.js', 'client');
  api.addFiles('lib/lang/tr.js', 'client');

  // Themes
  api.addFiles('lib/themes/black.js', 'client');
  api.addFiles('lib/themes/chalk.js', 'client');
  api.addFiles('lib/themes/dark.js', 'client');
  api.addFiles('lib/themes/light.js', 'client');
  api.addFiles('lib/themes/patterns.js', 'client');

  // Plugins
  api.addFiles('lib/plugins/dataloader/dataloader.min.js', 'client');
  api.addFiles('lib/plugins/dataloader/lang/en.js', 'client');
  api.addFiles('lib/plugins/dataloader/lang/lt.js', 'client');
  api.addFiles('lib/plugins/export/export.min.js', 'client');
  api.addFiles('lib/plugins/export/export.css', 'client');
  api.addFiles('lib/plugins/export/libs/blob.js/blob.js', 'client');
  api.addFiles('lib/plugins/export/libs/fabric.js/fabric.js', 'client');
  api.addFiles('lib/plugins/export/libs/FileSaver.js/FileSaver.js', 'client', {'bare':true});
  api.addFiles('lib/plugins/export/libs/jszip/jszip.js', 'client');
  // TODO These files cause a performance issue at compile
  // api.addFiles('lib/plugins/export/libs/pdfmake/pdfmake.js', 'client');
  // api.addFiles('lib/plugins/export/libs/pdfmake/vfs_fonts.js', 'client');
  api.addFiles('lib/plugins/export/libs/xlsx/xlsx.js', 'client', {'bare':true});
  api.addFiles('lib/plugins/responsive/responsive.min.js', 'client');

  // Assets can be accessed via the Assets API from the server, or at the URL /packages/em0ney_amcharts/ from the client
  api.addAssets('lib/images/dragIcon.gif', 'client');
  api.addAssets('lib/images/dragIconBlack.gif', 'client');
  api.addAssets('lib/images/dragIconH.gif', 'client');
  api.addAssets('lib/images/dragIconHBlack.gif', 'client');
  api.addAssets('lib/images/export.png', 'client');
  api.addAssets('lib/images/exportWhite.png', 'client');
  api.addAssets('lib/images/lens.png', 'client');
  api.addAssets('lib/images/dragIconRectBig.png', 'client');
  api.addAssets('lib/images/dragIconRectBig.svg', 'client');
  api.addAssets('lib/images/dragIconRectBigBlack.png', 'client');
  api.addAssets('lib/images/dragIconRectBigBlack.svg', 'client');
  api.addAssets('lib/images/dragIconRectBigBlackH.png', 'client');
  api.addAssets('lib/images/dragIconRectBigBlackH.svg', 'client');
  api.addAssets('lib/images/dragIconRectBigH.png', 'client');
  api.addAssets('lib/images/dragIconRectBigH.svg', 'client');
  api.addAssets('lib/images/dragIconRectSmall.png', 'client');
  api.addAssets('lib/images/dragIconRectSmall.svg', 'client');
  api.addAssets('lib/images/dragIconRectSmallBlack.png', 'client');
  api.addAssets('lib/images/dragIconRectSmallBlack.svg', 'client');
  api.addAssets('lib/images/dragIconRectSmallBlackH.png', 'client');
  api.addAssets('lib/images/dragIconRectSmallBlackH.svg', 'client');
  api.addAssets('lib/images/dragIconRectSmallH.png', 'client');
  api.addAssets('lib/images/dragIconRectSmallH.svg', 'client');
  api.addAssets('lib/images/dragIconRoundBig.png', 'client');
  api.addAssets('lib/images/dragIconRoundBig.svg', 'client');
  api.addAssets('lib/images/dragIconRoundBigBlack.png', 'client');
  api.addAssets('lib/images/dragIconRoundBigBlack.svg', 'client');
  api.addAssets('lib/images/dragIconRoundBigBlackH.png', 'client');
  api.addAssets('lib/images/dragIconRoundBigBlackH.svg', 'client');
  api.addAssets('lib/images/dragIconRoundBigH.png', 'client');
  api.addAssets('lib/images/dragIconRoundBigH.svg', 'client');
  api.addAssets('lib/images/dragIconRoundSmall.png', 'client');
  api.addAssets('lib/images/dragIconRoundSmall.svg', 'client');
  api.addAssets('lib/images/dragIconRoundSmallBlack.png', 'client');
  api.addAssets('lib/images/dragIconRoundSmallBlack.svg', 'client');
  api.addAssets('lib/images/dragIconRoundSmallBlackH.png', 'client');
  api.addAssets('lib/images/dragIconRoundSmallBlackH.svg', 'client');
  api.addAssets('lib/images/dragIconRoundSmallH.png', 'client');
  api.addAssets('lib/images/dragIconRoundSmallH.svg', 'client');
  api.addAssets('lib/images/eraserIcon.svg', 'client');
  api.addAssets('lib/images/eraserIconH.svg', 'client');
  api.addAssets('lib/images/lens.svg', 'client');
  api.addAssets('lib/images/lensWhite_old.png', 'client');
  api.addAssets('lib/images/lens_old.png', 'client');
  api.addAssets('lib/images/pencilIcon.svg', 'client');
  api.addAssets('lib/images/pencilIconH.svg', 'client');
  api.addAssets('lib/images/xIcon.svg', 'client');
  api.addAssets('lib/images/xIconH.svg', 'client');
  api.addAssets('lib/patterns/black/pattern1.png', 'client');
  api.addAssets('lib/patterns/black/pattern10.png', 'client');
  api.addAssets('lib/patterns/black/pattern11.png', 'client');
  api.addAssets('lib/patterns/black/pattern12.png', 'client');
  api.addAssets('lib/patterns/black/pattern13.png', 'client');
  api.addAssets('lib/patterns/black/pattern14.png', 'client');
  api.addAssets('lib/patterns/black/pattern15.png', 'client');
  api.addAssets('lib/patterns/black/pattern16.png', 'client');
  api.addAssets('lib/patterns/black/pattern17.png', 'client');
  api.addAssets('lib/patterns/black/pattern18.png', 'client');
  api.addAssets('lib/patterns/black/pattern19.png', 'client');
  api.addAssets('lib/patterns/black/pattern2.png', 'client');
  api.addAssets('lib/patterns/black/pattern20.png', 'client');
  api.addAssets('lib/patterns/black/pattern21.png', 'client');
  api.addAssets('lib/patterns/black/pattern3.png', 'client');
  api.addAssets('lib/patterns/black/pattern4.png', 'client');
  api.addAssets('lib/patterns/black/pattern5.png', 'client');
  api.addAssets('lib/patterns/black/pattern6.png', 'client');
  api.addAssets('lib/patterns/black/pattern7.png', 'client');
  api.addAssets('lib/patterns/black/pattern8.png', 'client');
  api.addAssets('lib/patterns/black/pattern9.png', 'client');
  api.addAssets('lib/patterns/chalk/pattern1.jpg', 'client');
  api.addAssets('lib/patterns/chalk/pattern1r.jpg', 'client');
  api.addAssets('lib/patterns/chalk/pattern2.jpg', 'client');
  api.addAssets('lib/patterns/chalk/pattern3.jpg', 'client');
  api.addAssets('lib/patterns/chalk/pattern4.jpg', 'client');
  api.addAssets('lib/patterns/chalk/pattern5.jpg', 'client');
  api.addAssets('lib/patterns/chalk/pattern6.jpg', 'client');
  api.addAssets('lib/patterns/white/pattern1.png', 'client');
  api.addAssets('lib/patterns/white/pattern10.png', 'client');
  api.addAssets('lib/patterns/white/pattern11.png', 'client');
  api.addAssets('lib/patterns/white/pattern12.png', 'client');
  api.addAssets('lib/patterns/white/pattern13.png', 'client');
  api.addAssets('lib/patterns/white/pattern14.png', 'client');
  api.addAssets('lib/patterns/white/pattern15.png', 'client');
  api.addAssets('lib/patterns/white/pattern16.png', 'client');
  api.addAssets('lib/patterns/white/pattern17.png', 'client');
  api.addAssets('lib/patterns/white/pattern18.png', 'client');
  api.addAssets('lib/patterns/white/pattern19.png', 'client');
  api.addAssets('lib/patterns/white/pattern2.png', 'client');
  api.addAssets('lib/patterns/white/pattern20.png', 'client');
  api.addAssets('lib/patterns/white/pattern21.png', 'client');
  api.addAssets('lib/patterns/white/pattern3.png', 'client');
  api.addAssets('lib/patterns/white/pattern4.png', 'client');
  api.addAssets('lib/patterns/white/pattern5.png', 'client');
  api.addAssets('lib/patterns/white/pattern6.png', 'client');
  api.addAssets('lib/patterns/white/pattern7.png', 'client');
  api.addAssets('lib/patterns/white/pattern8.png', 'client');
  api.addAssets('lib/patterns/white/pattern9.png', 'client');
  api.addAssets('lib/plugins/export/shapes/1.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/2.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/3.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/4.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/5.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/6.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/7.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/8.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/9.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/10.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/11.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/12.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/13.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/14.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/15.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/16.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/17.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/18.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/19.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/20.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/21.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/22.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/23.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/24.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/25.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/26.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/27.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/28.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/29.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/30.svg', 'client');
  api.addAssets('lib/plugins/export/shapes/31.svg', 'client');

  api.export("AmCharts","client");
  api.export("saveAs","client");
  api.export("XLSX","client");
});
